### ISSUE TITLE
Incompatible with webpack

### ISSUE THREAD

**Issue by akaRem** [undoZen/fetch-bluebird#2]
$ gulp webpack
[19:36:15] Using gulpfile ~/Projects/calc3/gulpfile.js
[19:36:15] Starting 'webpack'...
[19:36:16] Version: webpack 1.8.11
    Asset    Size  Chunks             Chunk Names
bundle.js  1.9 kB       0  [emitted]  main

ERROR in ./~/fetch-bluebird/index.js
Module parse failed: /<...>/node_modules/fetch-bluebird/index.js Line 8: Illegal return statement
You may need an appropriate loader to handle this file type.
| if (fetch.Promise) {
|     if (fetch.Promise === Promise) {
|         return;
|     }
|     fetch.Promise = Promise;
 @ ./client/main.js 2:0-25
[19:36:16] Finished 'webpack' after 437 ms
- I dont provide gulp config because it's irrelevant to the issue

**Comment by undoZen** [comment]
1.0.3 added a wrap function, should solve this problem, didn't accually try in webpack. let me know if it still break
